// Code generated by go-swagger; DO NOT EDIT.

package user_route

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// UserRouteCreateReader is a Reader for the UserRouteCreate structure.
type UserRouteCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserRouteCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserRouteCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUserRouteCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUserRouteCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUserRouteCreateOK creates a UserRouteCreateOK with default headers values
func NewUserRouteCreateOK() *UserRouteCreateOK {
	return &UserRouteCreateOK{}
}

/* UserRouteCreateOK describes a response with status code 200, with default header values.

OK
*/
type UserRouteCreateOK struct {
	Payload []*models.UserRouteRoute
}

func (o *UserRouteCreateOK) Error() string {
	return fmt.Sprintf("[POST /v1/user/route/create][%d] userRouteCreateOK  %+v", 200, o.Payload)
}
func (o *UserRouteCreateOK) GetPayload() []*models.UserRouteRoute {
	return o.Payload
}

func (o *UserRouteCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserRouteCreateBadRequest creates a UserRouteCreateBadRequest with default headers values
func NewUserRouteCreateBadRequest() *UserRouteCreateBadRequest {
	return &UserRouteCreateBadRequest{}
}

/* UserRouteCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UserRouteCreateBadRequest struct {
	Payload *models.UtilResponseWithError
}

func (o *UserRouteCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/user/route/create][%d] userRouteCreateBadRequest  %+v", 400, o.Payload)
}
func (o *UserRouteCreateBadRequest) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *UserRouteCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserRouteCreateInternalServerError creates a UserRouteCreateInternalServerError with default headers values
func NewUserRouteCreateInternalServerError() *UserRouteCreateInternalServerError {
	return &UserRouteCreateInternalServerError{}
}

/* UserRouteCreateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type UserRouteCreateInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *UserRouteCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/user/route/create][%d] userRouteCreateInternalServerError  %+v", 500, o.Payload)
}
func (o *UserRouteCreateInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *UserRouteCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
