// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// NewUserGetByNameParams creates a new UserGetByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserGetByNameParams() *UserGetByNameParams {
	return &UserGetByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserGetByNameParamsWithTimeout creates a new UserGetByNameParams object
// with the ability to set a timeout on a request.
func NewUserGetByNameParamsWithTimeout(timeout time.Duration) *UserGetByNameParams {
	return &UserGetByNameParams{
		timeout: timeout,
	}
}

// NewUserGetByNameParamsWithContext creates a new UserGetByNameParams object
// with the ability to set a context for a request.
func NewUserGetByNameParamsWithContext(ctx context.Context) *UserGetByNameParams {
	return &UserGetByNameParams{
		Context: ctx,
	}
}

// NewUserGetByNameParamsWithHTTPClient creates a new UserGetByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserGetByNameParamsWithHTTPClient(client *http.Client) *UserGetByNameParams {
	return &UserGetByNameParams{
		HTTPClient: client,
	}
}

/* UserGetByNameParams contains all the parameters to send to the API endpoint
   for the user get by name operation.

   Typically these are written to a http.Request.
*/
type UserGetByNameParams struct {

	/* Req.

	   request
	*/
	Req *models.UserGetByIDRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user get by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserGetByNameParams) WithDefaults() *UserGetByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user get by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserGetByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user get by name params
func (o *UserGetByNameParams) WithTimeout(timeout time.Duration) *UserGetByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user get by name params
func (o *UserGetByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user get by name params
func (o *UserGetByNameParams) WithContext(ctx context.Context) *UserGetByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user get by name params
func (o *UserGetByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user get by name params
func (o *UserGetByNameParams) WithHTTPClient(client *http.Client) *UserGetByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user get by name params
func (o *UserGetByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the user get by name params
func (o *UserGetByNameParams) WithReq(req *models.UserGetByIDRequest) *UserGetByNameParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the user get by name params
func (o *UserGetByNameParams) SetReq(req *models.UserGetByIDRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *UserGetByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
