// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// NewUserUpdateParams creates a new UserUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserUpdateParams() *UserUpdateParams {
	return &UserUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserUpdateParamsWithTimeout creates a new UserUpdateParams object
// with the ability to set a timeout on a request.
func NewUserUpdateParamsWithTimeout(timeout time.Duration) *UserUpdateParams {
	return &UserUpdateParams{
		timeout: timeout,
	}
}

// NewUserUpdateParamsWithContext creates a new UserUpdateParams object
// with the ability to set a context for a request.
func NewUserUpdateParamsWithContext(ctx context.Context) *UserUpdateParams {
	return &UserUpdateParams{
		Context: ctx,
	}
}

// NewUserUpdateParamsWithHTTPClient creates a new UserUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserUpdateParamsWithHTTPClient(client *http.Client) *UserUpdateParams {
	return &UserUpdateParams{
		HTTPClient: client,
	}
}

/* UserUpdateParams contains all the parameters to send to the API endpoint
   for the user update operation.

   Typically these are written to a http.Request.
*/
type UserUpdateParams struct {

	/* Req.

	   request
	*/
	Req *models.UserUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserUpdateParams) WithDefaults() *UserUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user update params
func (o *UserUpdateParams) WithTimeout(timeout time.Duration) *UserUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user update params
func (o *UserUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user update params
func (o *UserUpdateParams) WithContext(ctx context.Context) *UserUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user update params
func (o *UserUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user update params
func (o *UserUpdateParams) WithHTTPClient(client *http.Client) *UserUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user update params
func (o *UserUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the user update params
func (o *UserUpdateParams) WithReq(req *models.UserUpdateRequest) *UserUpdateParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the user update params
func (o *UserUpdateParams) SetReq(req *models.UserUpdateRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *UserUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
