// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// UserGetByLoginReader is a Reader for the UserGetByLogin structure.
type UserGetByLoginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserGetByLoginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserGetByLoginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUserGetByLoginBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUserGetByLoginNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUserGetByLoginInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUserGetByLoginOK creates a UserGetByLoginOK with default headers values
func NewUserGetByLoginOK() *UserGetByLoginOK {
	return &UserGetByLoginOK{}
}

/* UserGetByLoginOK describes a response with status code 200, with default header values.

OK
*/
type UserGetByLoginOK struct {
	Payload *models.UserGetResponse
}

func (o *UserGetByLoginOK) Error() string {
	return fmt.Sprintf("[POST /v1/user/getByLogin][%d] userGetByLoginOK  %+v", 200, o.Payload)
}
func (o *UserGetByLoginOK) GetPayload() *models.UserGetResponse {
	return o.Payload
}

func (o *UserGetByLoginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserGetByLoginBadRequest creates a UserGetByLoginBadRequest with default headers values
func NewUserGetByLoginBadRequest() *UserGetByLoginBadRequest {
	return &UserGetByLoginBadRequest{}
}

/* UserGetByLoginBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UserGetByLoginBadRequest struct {
	Payload *models.UtilResponseWithError
}

func (o *UserGetByLoginBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/user/getByLogin][%d] userGetByLoginBadRequest  %+v", 400, o.Payload)
}
func (o *UserGetByLoginBadRequest) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *UserGetByLoginBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserGetByLoginNotFound creates a UserGetByLoginNotFound with default headers values
func NewUserGetByLoginNotFound() *UserGetByLoginNotFound {
	return &UserGetByLoginNotFound{}
}

/* UserGetByLoginNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UserGetByLoginNotFound struct {
	Payload *models.UtilResponseWithError
}

func (o *UserGetByLoginNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/user/getByLogin][%d] userGetByLoginNotFound  %+v", 404, o.Payload)
}
func (o *UserGetByLoginNotFound) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *UserGetByLoginNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserGetByLoginInternalServerError creates a UserGetByLoginInternalServerError with default headers values
func NewUserGetByLoginInternalServerError() *UserGetByLoginInternalServerError {
	return &UserGetByLoginInternalServerError{}
}

/* UserGetByLoginInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type UserGetByLoginInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *UserGetByLoginInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/user/getByLogin][%d] userGetByLoginInternalServerError  %+v", 500, o.Payload)
}
func (o *UserGetByLoginInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *UserGetByLoginInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
