// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// NewUserGetByLoginParams creates a new UserGetByLoginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserGetByLoginParams() *UserGetByLoginParams {
	return &UserGetByLoginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserGetByLoginParamsWithTimeout creates a new UserGetByLoginParams object
// with the ability to set a timeout on a request.
func NewUserGetByLoginParamsWithTimeout(timeout time.Duration) *UserGetByLoginParams {
	return &UserGetByLoginParams{
		timeout: timeout,
	}
}

// NewUserGetByLoginParamsWithContext creates a new UserGetByLoginParams object
// with the ability to set a context for a request.
func NewUserGetByLoginParamsWithContext(ctx context.Context) *UserGetByLoginParams {
	return &UserGetByLoginParams{
		Context: ctx,
	}
}

// NewUserGetByLoginParamsWithHTTPClient creates a new UserGetByLoginParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserGetByLoginParamsWithHTTPClient(client *http.Client) *UserGetByLoginParams {
	return &UserGetByLoginParams{
		HTTPClient: client,
	}
}

/* UserGetByLoginParams contains all the parameters to send to the API endpoint
   for the user get by login operation.

   Typically these are written to a http.Request.
*/
type UserGetByLoginParams struct {

	/* Req.

	   request
	*/
	Req *models.UserGetByLoginRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user get by login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserGetByLoginParams) WithDefaults() *UserGetByLoginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user get by login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserGetByLoginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user get by login params
func (o *UserGetByLoginParams) WithTimeout(timeout time.Duration) *UserGetByLoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user get by login params
func (o *UserGetByLoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user get by login params
func (o *UserGetByLoginParams) WithContext(ctx context.Context) *UserGetByLoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user get by login params
func (o *UserGetByLoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user get by login params
func (o *UserGetByLoginParams) WithHTTPClient(client *http.Client) *UserGetByLoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user get by login params
func (o *UserGetByLoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the user get by login params
func (o *UserGetByLoginParams) WithReq(req *models.UserGetByLoginRequest) *UserGetByLoginParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the user get by login params
func (o *UserGetByLoginParams) SetReq(req *models.UserGetByLoginRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *UserGetByLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
