// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// UserGetByNameReader is a Reader for the UserGetByName structure.
type UserGetByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserGetByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserGetByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUserGetByNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUserGetByNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUserGetByNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUserGetByNameOK creates a UserGetByNameOK with default headers values
func NewUserGetByNameOK() *UserGetByNameOK {
	return &UserGetByNameOK{}
}

/* UserGetByNameOK describes a response with status code 200, with default header values.

OK
*/
type UserGetByNameOK struct {
	Payload *models.UserGetResponse
}

func (o *UserGetByNameOK) Error() string {
	return fmt.Sprintf("[POST /v1/user/getByLogin][%d] userGetByNameOK  %+v", 200, o.Payload)
}
func (o *UserGetByNameOK) GetPayload() *models.UserGetResponse {
	return o.Payload
}

func (o *UserGetByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserGetByNameBadRequest creates a UserGetByNameBadRequest with default headers values
func NewUserGetByNameBadRequest() *UserGetByNameBadRequest {
	return &UserGetByNameBadRequest{}
}

/* UserGetByNameBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UserGetByNameBadRequest struct {
	Payload *models.UtilResponseWithError
}

func (o *UserGetByNameBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/user/getByLogin][%d] userGetByNameBadRequest  %+v", 400, o.Payload)
}
func (o *UserGetByNameBadRequest) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *UserGetByNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserGetByNameNotFound creates a UserGetByNameNotFound with default headers values
func NewUserGetByNameNotFound() *UserGetByNameNotFound {
	return &UserGetByNameNotFound{}
}

/* UserGetByNameNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UserGetByNameNotFound struct {
	Payload *models.UtilResponseWithError
}

func (o *UserGetByNameNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/user/getByLogin][%d] userGetByNameNotFound  %+v", 404, o.Payload)
}
func (o *UserGetByNameNotFound) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *UserGetByNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserGetByNameInternalServerError creates a UserGetByNameInternalServerError with default headers values
func NewUserGetByNameInternalServerError() *UserGetByNameInternalServerError {
	return &UserGetByNameInternalServerError{}
}

/* UserGetByNameInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type UserGetByNameInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *UserGetByNameInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/user/getByLogin][%d] userGetByNameInternalServerError  %+v", 500, o.Payload)
}
func (o *UserGetByNameInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *UserGetByNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
