// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// NewSystemDeleteParams creates a new SystemDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSystemDeleteParams() *SystemDeleteParams {
	return &SystemDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSystemDeleteParamsWithTimeout creates a new SystemDeleteParams object
// with the ability to set a timeout on a request.
func NewSystemDeleteParamsWithTimeout(timeout time.Duration) *SystemDeleteParams {
	return &SystemDeleteParams{
		timeout: timeout,
	}
}

// NewSystemDeleteParamsWithContext creates a new SystemDeleteParams object
// with the ability to set a context for a request.
func NewSystemDeleteParamsWithContext(ctx context.Context) *SystemDeleteParams {
	return &SystemDeleteParams{
		Context: ctx,
	}
}

// NewSystemDeleteParamsWithHTTPClient creates a new SystemDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewSystemDeleteParamsWithHTTPClient(client *http.Client) *SystemDeleteParams {
	return &SystemDeleteParams{
		HTTPClient: client,
	}
}

/* SystemDeleteParams contains all the parameters to send to the API endpoint
   for the system delete operation.

   Typically these are written to a http.Request.
*/
type SystemDeleteParams struct {

	/* Req.

	   request
	*/
	Req *models.SystemDeleteRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the system delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemDeleteParams) WithDefaults() *SystemDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the system delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the system delete params
func (o *SystemDeleteParams) WithTimeout(timeout time.Duration) *SystemDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the system delete params
func (o *SystemDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the system delete params
func (o *SystemDeleteParams) WithContext(ctx context.Context) *SystemDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the system delete params
func (o *SystemDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the system delete params
func (o *SystemDeleteParams) WithHTTPClient(client *http.Client) *SystemDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the system delete params
func (o *SystemDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the system delete params
func (o *SystemDeleteParams) WithReq(req *models.SystemDeleteRequest) *SystemDeleteParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the system delete params
func (o *SystemDeleteParams) SetReq(req *models.SystemDeleteRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *SystemDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
