// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// SystemListReader is a Reader for the SystemList structure.
type SystemListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewSystemListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSystemListOK creates a SystemListOK with default headers values
func NewSystemListOK() *SystemListOK {
	return &SystemListOK{}
}

/* SystemListOK describes a response with status code 200, with default header values.

OK
*/
type SystemListOK struct {
	Payload []*models.SystemSystem
}

func (o *SystemListOK) Error() string {
	return fmt.Sprintf("[POST /v1/system/list][%d] systemListOK  %+v", 200, o.Payload)
}
func (o *SystemListOK) GetPayload() []*models.SystemSystem {
	return o.Payload
}

func (o *SystemListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemListInternalServerError creates a SystemListInternalServerError with default headers values
func NewSystemListInternalServerError() *SystemListInternalServerError {
	return &SystemListInternalServerError{}
}

/* SystemListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type SystemListInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *SystemListInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/system/list][%d] systemListInternalServerError  %+v", 500, o.Payload)
}
func (o *SystemListInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *SystemListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
