// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// SystemDeleteReader is a Reader for the SystemDelete structure.
type SystemDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSystemDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSystemDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSystemDeleteOK creates a SystemDeleteOK with default headers values
func NewSystemDeleteOK() *SystemDeleteOK {
	return &SystemDeleteOK{}
}

/* SystemDeleteOK describes a response with status code 200, with default header values.

SystemDeleteOK system delete o k
*/
type SystemDeleteOK struct {
}

func (o *SystemDeleteOK) Error() string {
	return fmt.Sprintf("[POST /v1/system/delete][%d] systemDeleteOK ", 200)
}

func (o *SystemDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSystemDeleteBadRequest creates a SystemDeleteBadRequest with default headers values
func NewSystemDeleteBadRequest() *SystemDeleteBadRequest {
	return &SystemDeleteBadRequest{}
}

/* SystemDeleteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type SystemDeleteBadRequest struct {
	Payload *models.UtilResponseWithError
}

func (o *SystemDeleteBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/system/delete][%d] systemDeleteBadRequest  %+v", 400, o.Payload)
}
func (o *SystemDeleteBadRequest) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *SystemDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemDeleteInternalServerError creates a SystemDeleteInternalServerError with default headers values
func NewSystemDeleteInternalServerError() *SystemDeleteInternalServerError {
	return &SystemDeleteInternalServerError{}
}

/* SystemDeleteInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type SystemDeleteInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *SystemDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/system/delete][%d] systemDeleteInternalServerError  %+v", 500, o.Payload)
}
func (o *SystemDeleteInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *SystemDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
