// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSystemListParams creates a new SystemListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSystemListParams() *SystemListParams {
	return &SystemListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSystemListParamsWithTimeout creates a new SystemListParams object
// with the ability to set a timeout on a request.
func NewSystemListParamsWithTimeout(timeout time.Duration) *SystemListParams {
	return &SystemListParams{
		timeout: timeout,
	}
}

// NewSystemListParamsWithContext creates a new SystemListParams object
// with the ability to set a context for a request.
func NewSystemListParamsWithContext(ctx context.Context) *SystemListParams {
	return &SystemListParams{
		Context: ctx,
	}
}

// NewSystemListParamsWithHTTPClient creates a new SystemListParams object
// with the ability to set a custom HTTPClient for a request.
func NewSystemListParamsWithHTTPClient(client *http.Client) *SystemListParams {
	return &SystemListParams{
		HTTPClient: client,
	}
}

/* SystemListParams contains all the parameters to send to the API endpoint
   for the system list operation.

   Typically these are written to a http.Request.
*/
type SystemListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the system list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemListParams) WithDefaults() *SystemListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the system list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the system list params
func (o *SystemListParams) WithTimeout(timeout time.Duration) *SystemListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the system list params
func (o *SystemListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the system list params
func (o *SystemListParams) WithContext(ctx context.Context) *SystemListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the system list params
func (o *SystemListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the system list params
func (o *SystemListParams) WithHTTPClient(client *http.Client) *SystemListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the system list params
func (o *SystemListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SystemListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
