env: "prod"
backend:
  port: :4000
database:
  #defauilt, can be overwritten by $BZDACS_POSTGRES env
  postgres: "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"
user:
  #defauilt, can be overwritten by $BZDACS_LOGIN env
  login: admin
  #defauilt, can be overwritten by $BZDACS_PASSWORD env
  password: admin
proxy:
  port: :8080
ui:
 path: /opt/bzdacs/ui
 port: :3000


