env: "prod"
host: http://localhost:8080
backend:
  port: :4000
proxy:
  port: :8080
ui:
  path: /opt/bzdacs/ui
#  path: /home/hs/go/src/github.com/hardstylez72/bzdacs/ui/dist
  port: :3000

database:
  #defauilt, can be overwritten by $BZDACS_POSTGRES env
  postgres: "host=localhost port=6667 user=postgres password=postgres dbname=postgres sslmode=disable"

internal:
  #defauilt, can be overwritten by $BZDACS_LOGIN env
  login: hs
  #defauilt, can be overwritten by $BZDACS_PASSWORD env
  password: 1234
  #defauilt, can be overwritten by $BZDACS_SESSION_LIFETIME_IN_SECONDS env
  sessionExpirationInSeconds: 600

  defaultNamespaceName: default

  system: BZDACS
  namespace: internal
  adminGroupName: admin
  adminGroupDescription: internal admin system group, all grants

  hasGuest: true
  guestGroupName: guest
  guestGroupDescription: internal guest system group, grunts for views



