// Code generated by go-swagger; DO NOT EDIT.

package route

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// NewRouteListParams creates a new RouteListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRouteListParams() *RouteListParams {
	return &RouteListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRouteListParamsWithTimeout creates a new RouteListParams object
// with the ability to set a timeout on a request.
func NewRouteListParamsWithTimeout(timeout time.Duration) *RouteListParams {
	return &RouteListParams{
		timeout: timeout,
	}
}

// NewRouteListParamsWithContext creates a new RouteListParams object
// with the ability to set a context for a request.
func NewRouteListParamsWithContext(ctx context.Context) *RouteListParams {
	return &RouteListParams{
		Context: ctx,
	}
}

// NewRouteListParamsWithHTTPClient creates a new RouteListParams object
// with the ability to set a custom HTTPClient for a request.
func NewRouteListParamsWithHTTPClient(client *http.Client) *RouteListParams {
	return &RouteListParams{
		HTTPClient: client,
	}
}

/* RouteListParams contains all the parameters to send to the API endpoint
   for the route list operation.

   Typically these are written to a http.Request.
*/
type RouteListParams struct {

	/* Req.

	   request
	*/
	Req *models.RouteListRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the route list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteListParams) WithDefaults() *RouteListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the route list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the route list params
func (o *RouteListParams) WithTimeout(timeout time.Duration) *RouteListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the route list params
func (o *RouteListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the route list params
func (o *RouteListParams) WithContext(ctx context.Context) *RouteListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the route list params
func (o *RouteListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the route list params
func (o *RouteListParams) WithHTTPClient(client *http.Client) *RouteListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the route list params
func (o *RouteListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the route list params
func (o *RouteListParams) WithReq(req *models.RouteListRequest) *RouteListParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the route list params
func (o *RouteListParams) SetReq(req *models.RouteListRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *RouteListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
