// Code generated by go-swagger; DO NOT EDIT.

package route

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// RouteDeleteReader is a Reader for the RouteDelete structure.
type RouteDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRouteDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRouteDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRouteDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRouteDeleteOK creates a RouteDeleteOK with default headers values
func NewRouteDeleteOK() *RouteDeleteOK {
	return &RouteDeleteOK{}
}

/* RouteDeleteOK describes a response with status code 200, with default header values.

RouteDeleteOK route delete o k
*/
type RouteDeleteOK struct {
}

func (o *RouteDeleteOK) Error() string {
	return fmt.Sprintf("[POST /v1/route/delete][%d] routeDeleteOK ", 200)
}

func (o *RouteDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRouteDeleteBadRequest creates a RouteDeleteBadRequest with default headers values
func NewRouteDeleteBadRequest() *RouteDeleteBadRequest {
	return &RouteDeleteBadRequest{}
}

/* RouteDeleteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RouteDeleteBadRequest struct {
	Payload *models.UtilResponseWithError
}

func (o *RouteDeleteBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/route/delete][%d] routeDeleteBadRequest  %+v", 400, o.Payload)
}
func (o *RouteDeleteBadRequest) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *RouteDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRouteDeleteInternalServerError creates a RouteDeleteInternalServerError with default headers values
func NewRouteDeleteInternalServerError() *RouteDeleteInternalServerError {
	return &RouteDeleteInternalServerError{}
}

/* RouteDeleteInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type RouteDeleteInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *RouteDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/route/delete][%d] routeDeleteInternalServerError  %+v", 500, o.Payload)
}
func (o *RouteDeleteInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *RouteDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
