// Code generated by go-swagger; DO NOT EDIT.

package route

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// NewRouteGetByIDParams creates a new RouteGetByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRouteGetByIDParams() *RouteGetByIDParams {
	return &RouteGetByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRouteGetByIDParamsWithTimeout creates a new RouteGetByIDParams object
// with the ability to set a timeout on a request.
func NewRouteGetByIDParamsWithTimeout(timeout time.Duration) *RouteGetByIDParams {
	return &RouteGetByIDParams{
		timeout: timeout,
	}
}

// NewRouteGetByIDParamsWithContext creates a new RouteGetByIDParams object
// with the ability to set a context for a request.
func NewRouteGetByIDParamsWithContext(ctx context.Context) *RouteGetByIDParams {
	return &RouteGetByIDParams{
		Context: ctx,
	}
}

// NewRouteGetByIDParamsWithHTTPClient creates a new RouteGetByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewRouteGetByIDParamsWithHTTPClient(client *http.Client) *RouteGetByIDParams {
	return &RouteGetByIDParams{
		HTTPClient: client,
	}
}

/* RouteGetByIDParams contains all the parameters to send to the API endpoint
   for the route get by Id operation.

   Typically these are written to a http.Request.
*/
type RouteGetByIDParams struct {

	/* Req.

	   request
	*/
	Req *models.RouteGetByIDRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the route get by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteGetByIDParams) WithDefaults() *RouteGetByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the route get by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteGetByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the route get by Id params
func (o *RouteGetByIDParams) WithTimeout(timeout time.Duration) *RouteGetByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the route get by Id params
func (o *RouteGetByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the route get by Id params
func (o *RouteGetByIDParams) WithContext(ctx context.Context) *RouteGetByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the route get by Id params
func (o *RouteGetByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the route get by Id params
func (o *RouteGetByIDParams) WithHTTPClient(client *http.Client) *RouteGetByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the route get by Id params
func (o *RouteGetByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the route get by Id params
func (o *RouteGetByIDParams) WithReq(req *models.RouteGetByIDRequest) *RouteGetByIDParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the route get by Id params
func (o *RouteGetByIDParams) SetReq(req *models.RouteGetByIDRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *RouteGetByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
