// Code generated by go-swagger; DO NOT EDIT.

package route

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// NewRouteCreateParams creates a new RouteCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRouteCreateParams() *RouteCreateParams {
	return &RouteCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRouteCreateParamsWithTimeout creates a new RouteCreateParams object
// with the ability to set a timeout on a request.
func NewRouteCreateParamsWithTimeout(timeout time.Duration) *RouteCreateParams {
	return &RouteCreateParams{
		timeout: timeout,
	}
}

// NewRouteCreateParamsWithContext creates a new RouteCreateParams object
// with the ability to set a context for a request.
func NewRouteCreateParamsWithContext(ctx context.Context) *RouteCreateParams {
	return &RouteCreateParams{
		Context: ctx,
	}
}

// NewRouteCreateParamsWithHTTPClient creates a new RouteCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewRouteCreateParamsWithHTTPClient(client *http.Client) *RouteCreateParams {
	return &RouteCreateParams{
		HTTPClient: client,
	}
}

/* RouteCreateParams contains all the parameters to send to the API endpoint
   for the route create operation.

   Typically these are written to a http.Request.
*/
type RouteCreateParams struct {

	/* Req.

	   request
	*/
	Req *models.RouteInsertRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the route create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteCreateParams) WithDefaults() *RouteCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the route create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the route create params
func (o *RouteCreateParams) WithTimeout(timeout time.Duration) *RouteCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the route create params
func (o *RouteCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the route create params
func (o *RouteCreateParams) WithContext(ctx context.Context) *RouteCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the route create params
func (o *RouteCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the route create params
func (o *RouteCreateParams) WithHTTPClient(client *http.Client) *RouteCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the route create params
func (o *RouteCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the route create params
func (o *RouteCreateParams) WithReq(req *models.RouteInsertRequest) *RouteCreateParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the route create params
func (o *RouteCreateParams) SetReq(req *models.RouteInsertRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *RouteCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
