// Code generated by go-swagger; DO NOT EDIT.

package route

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// NewRouteUpdateParams creates a new RouteUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRouteUpdateParams() *RouteUpdateParams {
	return &RouteUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRouteUpdateParamsWithTimeout creates a new RouteUpdateParams object
// with the ability to set a timeout on a request.
func NewRouteUpdateParamsWithTimeout(timeout time.Duration) *RouteUpdateParams {
	return &RouteUpdateParams{
		timeout: timeout,
	}
}

// NewRouteUpdateParamsWithContext creates a new RouteUpdateParams object
// with the ability to set a context for a request.
func NewRouteUpdateParamsWithContext(ctx context.Context) *RouteUpdateParams {
	return &RouteUpdateParams{
		Context: ctx,
	}
}

// NewRouteUpdateParamsWithHTTPClient creates a new RouteUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewRouteUpdateParamsWithHTTPClient(client *http.Client) *RouteUpdateParams {
	return &RouteUpdateParams{
		HTTPClient: client,
	}
}

/* RouteUpdateParams contains all the parameters to send to the API endpoint
   for the route update operation.

   Typically these are written to a http.Request.
*/
type RouteUpdateParams struct {

	/* Req.

	   request
	*/
	Req *models.RouteUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the route update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteUpdateParams) WithDefaults() *RouteUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the route update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the route update params
func (o *RouteUpdateParams) WithTimeout(timeout time.Duration) *RouteUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the route update params
func (o *RouteUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the route update params
func (o *RouteUpdateParams) WithContext(ctx context.Context) *RouteUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the route update params
func (o *RouteUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the route update params
func (o *RouteUpdateParams) WithHTTPClient(client *http.Client) *RouteUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the route update params
func (o *RouteUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the route update params
func (o *RouteUpdateParams) WithReq(req *models.RouteUpdateRequest) *RouteUpdateParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the route update params
func (o *RouteUpdateParams) SetReq(req *models.RouteUpdateRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *RouteUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
