// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// GroupGetByCodeReader is a Reader for the GroupGetByCode structure.
type GroupGetByCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupGetByCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupGetByCodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGroupGetByCodeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGroupGetByCodeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGroupGetByCodeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGroupGetByCodeOK creates a GroupGetByCodeOK with default headers values
func NewGroupGetByCodeOK() *GroupGetByCodeOK {
	return &GroupGetByCodeOK{}
}

/* GroupGetByCodeOK describes a response with status code 200, with default header values.

OK
*/
type GroupGetByCodeOK struct {
	Payload *models.GroupGetResponse
}

func (o *GroupGetByCodeOK) Error() string {
	return fmt.Sprintf("[POST /v1/group/getByCode][%d] groupGetByCodeOK  %+v", 200, o.Payload)
}
func (o *GroupGetByCodeOK) GetPayload() *models.GroupGetResponse {
	return o.Payload
}

func (o *GroupGetByCodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupGetByCodeBadRequest creates a GroupGetByCodeBadRequest with default headers values
func NewGroupGetByCodeBadRequest() *GroupGetByCodeBadRequest {
	return &GroupGetByCodeBadRequest{}
}

/* GroupGetByCodeBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GroupGetByCodeBadRequest struct {
	Payload *models.UtilResponseWithError
}

func (o *GroupGetByCodeBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/group/getByCode][%d] groupGetByCodeBadRequest  %+v", 400, o.Payload)
}
func (o *GroupGetByCodeBadRequest) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *GroupGetByCodeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupGetByCodeNotFound creates a GroupGetByCodeNotFound with default headers values
func NewGroupGetByCodeNotFound() *GroupGetByCodeNotFound {
	return &GroupGetByCodeNotFound{}
}

/* GroupGetByCodeNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GroupGetByCodeNotFound struct {
	Payload *models.UtilResponseWithError
}

func (o *GroupGetByCodeNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/group/getByCode][%d] groupGetByCodeNotFound  %+v", 404, o.Payload)
}
func (o *GroupGetByCodeNotFound) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *GroupGetByCodeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupGetByCodeInternalServerError creates a GroupGetByCodeInternalServerError with default headers values
func NewGroupGetByCodeInternalServerError() *GroupGetByCodeInternalServerError {
	return &GroupGetByCodeInternalServerError{}
}

/* GroupGetByCodeInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GroupGetByCodeInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *GroupGetByCodeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/group/getByCode][%d] groupGetByCodeInternalServerError  %+v", 500, o.Payload)
}
func (o *GroupGetByCodeInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *GroupGetByCodeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
