// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// GroupDeletesReader is a Reader for the GroupDeletes structure.
type GroupDeletesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupDeletesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupDeletesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGroupDeletesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGroupDeletesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGroupDeletesOK creates a GroupDeletesOK with default headers values
func NewGroupDeletesOK() *GroupDeletesOK {
	return &GroupDeletesOK{}
}

/* GroupDeletesOK describes a response with status code 200, with default header values.

GroupDeletesOK group deletes o k
*/
type GroupDeletesOK struct {
}

func (o *GroupDeletesOK) Error() string {
	return fmt.Sprintf("[POST /v1/group/delete][%d] groupDeletesOK ", 200)
}

func (o *GroupDeletesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGroupDeletesBadRequest creates a GroupDeletesBadRequest with default headers values
func NewGroupDeletesBadRequest() *GroupDeletesBadRequest {
	return &GroupDeletesBadRequest{}
}

/* GroupDeletesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GroupDeletesBadRequest struct {
	Payload *models.UtilResponseWithError
}

func (o *GroupDeletesBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/group/delete][%d] groupDeletesBadRequest  %+v", 400, o.Payload)
}
func (o *GroupDeletesBadRequest) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *GroupDeletesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupDeletesInternalServerError creates a GroupDeletesInternalServerError with default headers values
func NewGroupDeletesInternalServerError() *GroupDeletesInternalServerError {
	return &GroupDeletesInternalServerError{}
}

/* GroupDeletesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GroupDeletesInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *GroupDeletesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/group/delete][%d] groupDeletesInternalServerError  %+v", 500, o.Payload)
}
func (o *GroupDeletesInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *GroupDeletesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
