// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// NewNamespaceListParams creates a new NamespaceListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNamespaceListParams() *NamespaceListParams {
	return &NamespaceListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNamespaceListParamsWithTimeout creates a new NamespaceListParams object
// with the ability to set a timeout on a request.
func NewNamespaceListParamsWithTimeout(timeout time.Duration) *NamespaceListParams {
	return &NamespaceListParams{
		timeout: timeout,
	}
}

// NewNamespaceListParamsWithContext creates a new NamespaceListParams object
// with the ability to set a context for a request.
func NewNamespaceListParamsWithContext(ctx context.Context) *NamespaceListParams {
	return &NamespaceListParams{
		Context: ctx,
	}
}

// NewNamespaceListParamsWithHTTPClient creates a new NamespaceListParams object
// with the ability to set a custom HTTPClient for a request.
func NewNamespaceListParamsWithHTTPClient(client *http.Client) *NamespaceListParams {
	return &NamespaceListParams{
		HTTPClient: client,
	}
}

/* NamespaceListParams contains all the parameters to send to the API endpoint
   for the namespace list operation.

   Typically these are written to a http.Request.
*/
type NamespaceListParams struct {

	/* Req.

	   request
	*/
	Req *models.NamespaceListRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the namespace list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NamespaceListParams) WithDefaults() *NamespaceListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the namespace list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NamespaceListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the namespace list params
func (o *NamespaceListParams) WithTimeout(timeout time.Duration) *NamespaceListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the namespace list params
func (o *NamespaceListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the namespace list params
func (o *NamespaceListParams) WithContext(ctx context.Context) *NamespaceListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the namespace list params
func (o *NamespaceListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the namespace list params
func (o *NamespaceListParams) WithHTTPClient(client *http.Client) *NamespaceListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the namespace list params
func (o *NamespaceListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the namespace list params
func (o *NamespaceListParams) WithReq(req *models.NamespaceListRequest) *NamespaceListParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the namespace list params
func (o *NamespaceListParams) SetReq(req *models.NamespaceListRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *NamespaceListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
