// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// NamespaceListReader is a Reader for the NamespaceList structure.
type NamespaceListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NamespaceListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNamespaceListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNamespaceListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewNamespaceListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNamespaceListOK creates a NamespaceListOK with default headers values
func NewNamespaceListOK() *NamespaceListOK {
	return &NamespaceListOK{}
}

/* NamespaceListOK describes a response with status code 200, with default header values.

OK
*/
type NamespaceListOK struct {
	Payload []*models.NamespaceGetResponse
}

func (o *NamespaceListOK) Error() string {
	return fmt.Sprintf("[POST /v1/namespace/list][%d] namespaceListOK  %+v", 200, o.Payload)
}
func (o *NamespaceListOK) GetPayload() []*models.NamespaceGetResponse {
	return o.Payload
}

func (o *NamespaceListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNamespaceListBadRequest creates a NamespaceListBadRequest with default headers values
func NewNamespaceListBadRequest() *NamespaceListBadRequest {
	return &NamespaceListBadRequest{}
}

/* NamespaceListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type NamespaceListBadRequest struct {
	Payload *models.UtilResponseWithError
}

func (o *NamespaceListBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/namespace/list][%d] namespaceListBadRequest  %+v", 400, o.Payload)
}
func (o *NamespaceListBadRequest) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *NamespaceListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNamespaceListInternalServerError creates a NamespaceListInternalServerError with default headers values
func NewNamespaceListInternalServerError() *NamespaceListInternalServerError {
	return &NamespaceListInternalServerError{}
}

/* NamespaceListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type NamespaceListInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *NamespaceListInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/namespace/list][%d] namespaceListInternalServerError  %+v", 500, o.Payload)
}
func (o *NamespaceListInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *NamespaceListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
