// Code generated by go-swagger; DO NOT EDIT.

package user_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// UserGroupDeleteReader is a Reader for the UserGroupDelete structure.
type UserGroupDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserGroupDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserGroupDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUserGroupDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUserGroupDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUserGroupDeleteOK creates a UserGroupDeleteOK with default headers values
func NewUserGroupDeleteOK() *UserGroupDeleteOK {
	return &UserGroupDeleteOK{}
}

/* UserGroupDeleteOK describes a response with status code 200, with default header values.

UserGroupDeleteOK user group delete o k
*/
type UserGroupDeleteOK struct {
}

func (o *UserGroupDeleteOK) Error() string {
	return fmt.Sprintf("[POST /v1/user/group/delete][%d] userGroupDeleteOK ", 200)
}

func (o *UserGroupDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUserGroupDeleteBadRequest creates a UserGroupDeleteBadRequest with default headers values
func NewUserGroupDeleteBadRequest() *UserGroupDeleteBadRequest {
	return &UserGroupDeleteBadRequest{}
}

/* UserGroupDeleteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UserGroupDeleteBadRequest struct {
	Payload *models.UtilResponseWithError
}

func (o *UserGroupDeleteBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/user/group/delete][%d] userGroupDeleteBadRequest  %+v", 400, o.Payload)
}
func (o *UserGroupDeleteBadRequest) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *UserGroupDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserGroupDeleteInternalServerError creates a UserGroupDeleteInternalServerError with default headers values
func NewUserGroupDeleteInternalServerError() *UserGroupDeleteInternalServerError {
	return &UserGroupDeleteInternalServerError{}
}

/* UserGroupDeleteInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type UserGroupDeleteInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *UserGroupDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/user/group/delete][%d] userGroupDeleteInternalServerError  %+v", 500, o.Payload)
}
func (o *UserGroupDeleteInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *UserGroupDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
