// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// TagUpdateReader is a Reader for the TagUpdate structure.
type TagUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TagUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTagUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTagUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTagUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTagUpdateOK creates a TagUpdateOK with default headers values
func NewTagUpdateOK() *TagUpdateOK {
	return &TagUpdateOK{}
}

/* TagUpdateOK describes a response with status code 200, with default header values.

OK
*/
type TagUpdateOK struct {
	Payload *models.TagUpdateResponse
}

func (o *TagUpdateOK) Error() string {
	return fmt.Sprintf("[POST /v1/tag/update][%d] tagUpdateOK  %+v", 200, o.Payload)
}
func (o *TagUpdateOK) GetPayload() *models.TagUpdateResponse {
	return o.Payload
}

func (o *TagUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TagUpdateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTagUpdateBadRequest creates a TagUpdateBadRequest with default headers values
func NewTagUpdateBadRequest() *TagUpdateBadRequest {
	return &TagUpdateBadRequest{}
}

/* TagUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TagUpdateBadRequest struct {
	Payload *models.UtilResponseWithError
}

func (o *TagUpdateBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/tag/update][%d] tagUpdateBadRequest  %+v", 400, o.Payload)
}
func (o *TagUpdateBadRequest) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *TagUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTagUpdateInternalServerError creates a TagUpdateInternalServerError with default headers values
func NewTagUpdateInternalServerError() *TagUpdateInternalServerError {
	return &TagUpdateInternalServerError{}
}

/* TagUpdateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type TagUpdateInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *TagUpdateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/tag/update][%d] tagUpdateInternalServerError  %+v", 500, o.Payload)
}
func (o *TagUpdateInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *TagUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
