// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// TagListReader is a Reader for the TagList structure.
type TagListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TagListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTagListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTagListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTagListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTagListOK creates a TagListOK with default headers values
func NewTagListOK() *TagListOK {
	return &TagListOK{}
}

/* TagListOK describes a response with status code 200, with default header values.

OK
*/
type TagListOK struct {
	Payload []*models.TagTag
}

func (o *TagListOK) Error() string {
	return fmt.Sprintf("[POST /v1/tag/list][%d] tagListOK  %+v", 200, o.Payload)
}
func (o *TagListOK) GetPayload() []*models.TagTag {
	return o.Payload
}

func (o *TagListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTagListBadRequest creates a TagListBadRequest with default headers values
func NewTagListBadRequest() *TagListBadRequest {
	return &TagListBadRequest{}
}

/* TagListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TagListBadRequest struct {
	Payload *models.UtilResponseWithError
}

func (o *TagListBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/tag/list][%d] tagListBadRequest  %+v", 400, o.Payload)
}
func (o *TagListBadRequest) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *TagListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTagListInternalServerError creates a TagListInternalServerError with default headers values
func NewTagListInternalServerError() *TagListInternalServerError {
	return &TagListInternalServerError{}
}

/* TagListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type TagListInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *TagListInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/tag/list][%d] tagListInternalServerError  %+v", 500, o.Payload)
}
func (o *TagListInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *TagListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
