// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// NewTagDeleteParams creates a new TagDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTagDeleteParams() *TagDeleteParams {
	return &TagDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTagDeleteParamsWithTimeout creates a new TagDeleteParams object
// with the ability to set a timeout on a request.
func NewTagDeleteParamsWithTimeout(timeout time.Duration) *TagDeleteParams {
	return &TagDeleteParams{
		timeout: timeout,
	}
}

// NewTagDeleteParamsWithContext creates a new TagDeleteParams object
// with the ability to set a context for a request.
func NewTagDeleteParamsWithContext(ctx context.Context) *TagDeleteParams {
	return &TagDeleteParams{
		Context: ctx,
	}
}

// NewTagDeleteParamsWithHTTPClient creates a new TagDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewTagDeleteParamsWithHTTPClient(client *http.Client) *TagDeleteParams {
	return &TagDeleteParams{
		HTTPClient: client,
	}
}

/* TagDeleteParams contains all the parameters to send to the API endpoint
   for the tag delete operation.

   Typically these are written to a http.Request.
*/
type TagDeleteParams struct {

	/* Req.

	   request
	*/
	Req *models.TagDeleteRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the tag delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TagDeleteParams) WithDefaults() *TagDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the tag delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TagDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the tag delete params
func (o *TagDeleteParams) WithTimeout(timeout time.Duration) *TagDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tag delete params
func (o *TagDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tag delete params
func (o *TagDeleteParams) WithContext(ctx context.Context) *TagDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tag delete params
func (o *TagDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tag delete params
func (o *TagDeleteParams) WithHTTPClient(client *http.Client) *TagDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tag delete params
func (o *TagDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the tag delete params
func (o *TagDeleteParams) WithReq(req *models.TagDeleteRequest) *TagDeleteParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the tag delete params
func (o *TagDeleteParams) SetReq(req *models.TagDeleteRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *TagDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
