// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hardstylez72/bzdacs/models"
)

// TagCreateReader is a Reader for the TagCreate structure.
type TagCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TagCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTagCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTagCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewTagCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTagCreateOK creates a TagCreateOK with default headers values
func NewTagCreateOK() *TagCreateOK {
	return &TagCreateOK{}
}

/* TagCreateOK describes a response with status code 200, with default header values.

OK
*/
type TagCreateOK struct {
	Payload *models.TagGetResponse
}

func (o *TagCreateOK) Error() string {
	return fmt.Sprintf("[POST /v1/tag/create][%d] tagCreateOK  %+v", 200, o.Payload)
}
func (o *TagCreateOK) GetPayload() *models.TagGetResponse {
	return o.Payload
}

func (o *TagCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TagGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTagCreateBadRequest creates a TagCreateBadRequest with default headers values
func NewTagCreateBadRequest() *TagCreateBadRequest {
	return &TagCreateBadRequest{}
}

/* TagCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TagCreateBadRequest struct {
	Payload *models.UtilResponseWithError
}

func (o *TagCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/tag/create][%d] tagCreateBadRequest  %+v", 400, o.Payload)
}
func (o *TagCreateBadRequest) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *TagCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTagCreateInternalServerError creates a TagCreateInternalServerError with default headers values
func NewTagCreateInternalServerError() *TagCreateInternalServerError {
	return &TagCreateInternalServerError{}
}

/* TagCreateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type TagCreateInternalServerError struct {
	Payload *models.UtilResponseWithError
}

func (o *TagCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/tag/create][%d] tagCreateInternalServerError  %+v", 500, o.Payload)
}
func (o *TagCreateInternalServerError) GetPayload() *models.UtilResponseWithError {
	return o.Payload
}

func (o *TagCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilResponseWithError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
