// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GroupRouteDeleteRequest group route delete request
//
// swagger:model groupRouteDeleteRequest
type GroupRouteDeleteRequest struct {

	// pairs
	// Required: true
	Pairs []*GroupRoutePair `json:"pairs"`
}

// Validate validates this group route delete request
func (m *GroupRouteDeleteRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePairs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GroupRouteDeleteRequest) validatePairs(formats strfmt.Registry) error {

	if err := validate.Required("pairs", "body", m.Pairs); err != nil {
		return err
	}

	for i := 0; i < len(m.Pairs); i++ {
		if swag.IsZero(m.Pairs[i]) { // not required
			continue
		}

		if m.Pairs[i] != nil {
			if err := m.Pairs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pairs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this group route delete request based on the context it is used
func (m *GroupRouteDeleteRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePairs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GroupRouteDeleteRequest) contextValidatePairs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Pairs); i++ {

		if m.Pairs[i] != nil {
			if err := m.Pairs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pairs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GroupRouteDeleteRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GroupRouteDeleteRequest) UnmarshalBinary(b []byte) error {
	var res GroupRouteDeleteRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
