// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GrouproutePair grouproute pair
//
// swagger:model grouproute.Pair
type GrouproutePair struct {

	// group Id
	// Required: true
	GroupID *int64 `json:"groupId"`

	// route Id
	// Required: true
	RouteID *int64 `json:"routeId"`
}

// Validate validates this grouproute pair
func (m *GrouproutePair) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGroupID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRouteID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GrouproutePair) validateGroupID(formats strfmt.Registry) error {

	if err := validate.Required("groupId", "body", m.GroupID); err != nil {
		return err
	}

	return nil
}

func (m *GrouproutePair) validateRouteID(formats strfmt.Registry) error {

	if err := validate.Required("routeId", "body", m.RouteID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this grouproute pair based on context it is used
func (m *GrouproutePair) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GrouproutePair) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GrouproutePair) UnmarshalBinary(b []byte) error {
	var res GrouproutePair
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
