// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NamespaceInsertRequest namespace insert request
//
// swagger:model namespace.insertRequest
type NamespaceInsertRequest struct {

	// name
	// Required: true
	Name *string `json:"name"`

	// system Id
	// Required: true
	SystemID *int64 `json:"systemId"`
}

// Validate validates this namespace insert request
func (m *NamespaceInsertRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSystemID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NamespaceInsertRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *NamespaceInsertRequest) validateSystemID(formats strfmt.Registry) error {

	if err := validate.Required("systemId", "body", m.SystemID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this namespace insert request based on context it is used
func (m *NamespaceInsertRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NamespaceInsertRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NamespaceInsertRequest) UnmarshalBinary(b []byte) error {
	var res NamespaceInsertRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
