// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UtilError util error
//
// swagger:model util.Error
type UtilError struct {

	// code
	Code string `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// stack
	Stack string `json:"stack,omitempty"`
}

// Validate validates this util error
func (m *UtilError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this util error based on context it is used
func (m *UtilError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UtilError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UtilError) UnmarshalBinary(b []byte) error {
	var res UtilError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
